---
- name: Get OS Family of each Host
  hosts: all

  tasks:
    - name: Define OS Family Variable
      set_fact:
        host_os_family: ansible_os_family
        
    - name: Display variable value using debug module -- DEBUG
      debug:
        var: host_os_family
