---
- name: Get IP Address Type
  hosts: all
  # gather_facts: no  # No need to gather facts for this task

  tasks:
    - name: Block I - Get IP address Type on Windows Hosts
      block:
        - name: Run 'ipconfig /all' Command on PowerShell
          win_shell: ipconfig /all
          register: ip_config_result
          
        - name: Determine IP Address Type
          set_fact:
            ip_type: "{{ 'static' if ip_config_result.stdout_lines | map('regex_search', 'DHCP Enabled.*No') | select | list | length > 0 else 'dynamic' }}"
      when: ansible_os_family == "Windows"
      
    - name: Get IP address Type on Linux Hosts
      block: 
        - name: Run 'ip r' Command
          become: true
          vars:
            ansible_become_pass: "{{ ansible_password }}"
          shell: ip r
          register: ip_route_result
        
        - name: Determine IP Address Type
          set_fact:
            ip_type: "{{ 'static' if 'dhcp' not in ip_route_result.stdout else 'dynamic' }}"
        
      when: ansible_os_family ==  "Debian" or ansible_os_family ==  "RedHat"
      
    - name: Display IP address type
      debug:
        msg: "IP address type on {{ inventory_hostname }} ({{ ansible_os_family }}): {{ ip_type }}"
