---
- name: Set Host IP Type to Static
  hosts: all
  # gather_facts: no  # Disable fact gathering for this play

  tasks:
    - name: Block I - Set IP to Static on Windows Hosts
      block:
        - name: Get Current Net Adapter
          win_shell: Get-NetAdapter | Format-List
          register: net_adapter

        - name: Find InterfaceIndex
          set_fact:
            interface_index: "{{ net_adapter.stdout_lines | map('regex_search', 'InterfaceIndex.*') | select | list | first | regex_search('(\\d+)') }}"

        #- name: Remove IP Configuration
        #  win_shell: Remove-NetIPAddress -IPAddress {{ inventory_hostname }} -Confirm:$False
            
        - name: Set New IP Configuration
          win_shell: Set-NetIPAddress -InterfaceIndex {{ interface_index }} -IPAddress {{ inventory_hostname }} -PrefixLength 24

        - name: Set DNS Configuration
          win_shell: Set-DnsClientServerAddress -InterfaceIndex {{ interface_index }} -ServerAddresses 8.8.8.8,8.8.8.4
          
        - name: Report
          debug:
            msg: "IP configuration is successfuly done!"

          
      when: ansible_os_family == "Windows"

      
    - name: Block II - Set IP to Static on Debian Hosts
      block:
        - name: Get network configuration
          shell: sudo lshw -class network -json 
          register: network_data
      
        - name: Get network name
          set_fact: 
            desired_value: "{{ network_data.stdout | from_json | json_query('logicalname') }}"

        - name: Display network name
          debug:
            msg: "{{ desired_value }}"
      when: ansible_os_family == "Debian"
      
  handlers:
    - name: Apply Netplan Config
      command: netplan apply
